### ISSUE TITLE
Different box designs

### ISSUE THREAD

**Issue by matyasbohacek** [thanhdolong/sign-language-recognition-trainer#14]
**Describe the bug**
The box for video preview has slightly different color and shading in the **Annotate video** section.

**To Reproduce**
Open the app and compare the designs in the individual sections.

**Expected behavior**
A unified box design.

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1 Big Sur

**Comment by thanhdolong** [comment]
Problem solved
